# Generated by Django 6.0 on 2025-12-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeer',
            old_name='name',
            new_name='username',
        ),
    ]
