# Generated by Django 6.0 on 2025-12-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_name_employeer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeer',
            name='email',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
    ]
