# Generated by Django 6.0 on 2025-12-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeer',
            old_name='username',
            new_name='user',
        ),
    ]
