# Generated by Django 6.0 on 2025-12-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_username_employeer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
    ]
