# Generated by Django 6.0 on 2025-12-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_taskupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeer',
            name='foto',
            field=models.ImageField(default=False, upload_to='media/funcionarios'),
        ),
    ]
