# Generated by Django 6.0 on 2025-12-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeer_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeer',
            name='foto',
            field=models.ImageField(default=False, upload_to='funcionarios'),
        ),
    ]
