# Generated by Django 6.0 on 2025-12-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeer_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeer',
            name='Online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeer',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios'),
        ),
    ]
